# Generated by Django 5.1.4 on 2026-02-26 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('reddit', 'Reddit'), ('twitter', 'Twitter/X'), ('youtube', 'YouTube')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('query', models.CharField(max_length=500)),
                ('mentions_found', models.PositiveIntegerField(default=0)),
                ('mentions_new', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrape_jobs', to='titles.title')),
            ],
            options={
                'db_table': 'scrape_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SentimentMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('reddit', 'Reddit'), ('twitter', 'Twitter/X'), ('youtube', 'YouTube')], db_index=True, max_length=20)),
                ('source_id', models.CharField(max_length=200)),
                ('source_url', models.URLField(blank=True)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('subreddit', models.CharField(blank=True, max_length=100)),
                ('post_type', models.CharField(blank=True, max_length=20)),
                ('text', models.TextField()),
                ('text_length', models.PositiveIntegerField(default=0)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('mixed', 'Mixed')], db_index=True, max_length=10)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('positive_score', models.FloatField(blank=True, null=True)),
                ('negative_score', models.FloatField(blank=True, null=True)),
                ('neutral_score', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('reply_count', models.IntegerField(default=0)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='titles.title')),
            ],
            options={
                'db_table': 'sentiment_mentions',
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['title', 'source', '-posted_at'], name='sentiment_m_title_i_86e367_idx'), models.Index(fields=['title', 'sentiment'], name='sentiment_m_title_i_e2d825_idx'), models.Index(fields=['is_processed', '-scraped_at'], name='sentiment_m_is_proc_48306f_idx')],
                'unique_together': {('source', 'source_id')},
            },
        ),
        migrations.CreateModel(
            name='SentimentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], max_length=20)),
                ('snapshot_date', models.DateField()),
                ('positive_count', models.PositiveIntegerField(default=0)),
                ('negative_count', models.PositiveIntegerField(default=0)),
                ('neutral_count', models.PositiveIntegerField(default=0)),
                ('mixed_count', models.PositiveIntegerField(default=0)),
                ('total_mentions', models.PositiveIntegerField(default=0)),
                ('positive_pct', models.FloatField(default=0)),
                ('negative_pct', models.FloatField(default=0)),
                ('neutral_pct', models.FloatField(default=0)),
                ('avg_sentiment_score', models.FloatField(default=0)),
                ('senti_score', models.FloatField(default=0)),
                ('reddit_mentions', models.PositiveIntegerField(default=0)),
                ('twitter_mentions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_snapshots', to='titles.title')),
            ],
            options={
                'db_table': 'sentiment_snapshots',
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['title', 'period', '-snapshot_date'], name='sentiment_s_title_i_142cb4_idx')],
                'unique_together': {('title', 'period', 'snapshot_date')},
            },
        ),
    ]
