# Generated by Django 5.1.4 on 2026-02-26 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('anilist_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profile_image', models.URLField(blank=True)),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('anilist_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'people',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('original_title', models.CharField(blank=True, max_length=500)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('title_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Series'), ('anime', 'Anime')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('released', 'Released'), ('upcoming', 'Upcoming'), ('airing', 'Currently Airing'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='released', max_length=20)),
                ('overview', models.TextField(blank=True)),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('release_date', models.DateField(blank=True, db_index=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('runtime_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('original_language', models.CharField(blank=True, max_length=10)),
                ('poster_url', models.URLField(blank=True)),
                ('backdrop_url', models.URLField(blank=True)),
                ('poster_path', models.CharField(blank=True, max_length=200)),
                ('backdrop_path', models.CharField(blank=True, max_length=200)),
                ('tmdb_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('imdb_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('anilist_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('mal_id', models.IntegerField(blank=True, null=True)),
                ('tmdb_rating', models.FloatField(blank=True, null=True)),
                ('tmdb_vote_count', models.PositiveIntegerField(default=0)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('total_seasons', models.PositiveIntegerField(blank=True, null=True)),
                ('total_episodes', models.PositiveIntegerField(blank=True, null=True)),
                ('episode_runtime', models.PositiveIntegerField(blank=True, null=True)),
                ('studio', models.CharField(blank=True, max_length=200)),
                ('network', models.CharField(blank=True, max_length=200)),
                ('senti_score', models.FloatField(blank=True, null=True)),
                ('senti_positive_pct', models.FloatField(blank=True, null=True)),
                ('senti_negative_pct', models.FloatField(blank=True, null=True)),
                ('senti_neutral_pct', models.FloatField(blank=True, null=True)),
                ('senti_total_mentions', models.PositiveIntegerField(default=0)),
                ('senti_last_updated', models.DateTimeField(blank=True, null=True)),
                ('avg_user_rating', models.FloatField(blank=True, null=True)),
                ('total_user_ratings', models.PositiveIntegerField(default=0)),
                ('total_user_reviews', models.PositiveIntegerField(default=0)),
                ('total_watchlisted', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('directors', models.ManyToManyField(blank=True, related_name='directed_titles', to='titles.person')),
                ('genres', models.ManyToManyField(blank=True, related_name='titles', to='titles.genre')),
            ],
            options={
                'db_table': 'titles',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='TitleCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.person')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.title')),
            ],
            options={
                'db_table': 'title_cast',
                'ordering': ['order'],
                'unique_together': {('title', 'person', 'character_name')},
            },
        ),
        migrations.AddField(
            model_name='title',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='acted_in', through='titles.TitleCast', to='titles.person'),
        ),
        migrations.CreateModel(
            name='TitleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('image_type', models.CharField(choices=[('poster', 'Poster'), ('backdrop', 'Backdrop'), ('still', 'Still'), ('logo', 'Logo')], max_length=20)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='titles.title')),
            ],
            options={
                'db_table': 'title_images',
            },
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['title_type', '-release_date'], name='titles_title_t_a0d3f2_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['title_type', '-senti_score'], name='titles_title_t_3a1463_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['-senti_score'], name='titles_senti_s_a1a5f4_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['-avg_user_rating'], name='titles_avg_use_a1ca2c_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['tmdb_id', 'title_type'], name='titles_tmdb_id_d8b8a5_idx'),
        ),
    ]
